package se.trixon.toolbox.core.dialog;

import java.util.Collection;
import javax.swing.table.TableColumnModel;
import org.openide.util.Lookup;
import se.trixon.toolbox.core.ToolProvider;

/**
 *
 * @author Patrik Karlsson <patrik@trixon.se>
 */
public class ToolsListPanel extends javax.swing.JPanel {

    private final ToolsListTableModel mListTableModel = new ToolsListTableModel();

    /**
     * Creates new form ToolsListPanel
     */
    public ToolsListPanel() {
        initComponents();
        table.setModel(mListTableModel);
        table.setAutoCreateRowSorter(true);
        TableColumnModel columnModel = table.getColumnModel();

        columnModel.getColumn(ToolsListTableModel.COLUMN_NAME).setPreferredWidth(100);
        columnModel.getColumn(ToolsListTableModel.COLUMN_DESCRIPTION).setPreferredWidth(100);
        columnModel.getColumn(ToolsListTableModel.COLUMN_VERSION).setPreferredWidth(10);
        columnModel.getColumn(ToolsListTableModel.COLUMN_CATEGORY).setPreferredWidth(20);
        columnModel.getColumn(ToolsListTableModel.COLUMN_COPYRIGHT).setPreferredWidth(100);
        columnModel.getColumn(ToolsListTableModel.COLUMN_LICENSE).setPreferredWidth(40);

        Collection<? extends ToolProvider> toolProviders = Lookup.getDefault().lookupAll(ToolProvider.class);

        for (ToolProvider toolProvider : toolProviders) {
            mListTableModel.addRow(toolProvider);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        scrollPane.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
